name:                Haskell-Alpha
version:             1.0
github:              "davidhadhazi/Haskell-Alpha"
license:             BSD3
author:              "David Hadhazi"
maintainer:          "david.hadhazi@gmail.com"
copyright:           ""

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davidhadhazi/Haskell-Alpha#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk
- haskell-gi-base
- text
- Chart
- Chart-diagrams
- Chart-cairo
- colour
- lens
- data-default-class
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Haskell-Alpha-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-Alpha

tests:
  Haskell-Alpha-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-Alpha
    - HUnit
